// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxkshjaombffbdemqrqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94a3NoamFvbWJmZmJkZW1xcnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0NDc1ODAsImV4cCI6MjA4MDAyMzU4MH0.sOjGp5S6sKEcKm1xWolIjJpMpA__ncqDK8nJxbyJmYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});