// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxkshjaombffbdemqrqb.supabase.co";
// New-format publishable key. The legacy anon JWT was disabled platform-wide on
// 2026-04-20, which broke every frontend Supabase call (login, password reset, ...).
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_KJox5swPIcwq6PyTfDpAuQ_pyWGtqga";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});